services:
  - type: web
    name: webexam
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -w 2 -k gevent -b 0.0.0.0:$PORT
    autoDeploy: true

