services:
  - type: web
    name: lab6
    rootDir: lab6
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 2 -k gevent -b 0.0.0.0:$PORT
    autoDeploy: true

  - type: web
    name: webexam
    rootDir: WebExam
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -w 2 -k gevent -b 0.0.0.0:$PORT
    autoDeploy: true
services:
  - type: web
    name: lab2
    env: python
    plan: free
    rootDir: lab2
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

  - type: web
    name: lab3
    env: python
    plan: free
    rootDir: lab3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

  - type: web
    name: lab4
    env: python
    plan: free
    rootDir: lab4
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT

  - type: web
    name: lab5
    env: python
    plan: free
    rootDir: lab5
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT

  - type: web
    name: lab6
    env: python
    plan: free
    rootDir: lab6
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

  - type: web
    name: webexam
    env: python
    plan: free
    rootDir: WebExam
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT

